import type { HomeStrings } from './home'

export const es: HomeStrings = {
  meta: {
    htmlLang: 'es',
    title: 'Kevin Gámez - Founding Engineer en Enttor',
    description:
      'Kevin Gámez es founding engineer en Enttor, basado en Bogotá. Outbound con IA, automatización de navegador, pipelines de OpenAI, Next.js / NestJS / Postgres.',
    canonical: 'https://kevingamez.co/es/',
    ogUrl: 'https://kevingamez.co/es/',
    ogTitle: 'Kevin Gámez - Founding Engineer en Enttor',
    ogDescription:
      'Founding engineer en enttor.ai. Outbound con IA, automatización de navegador, pipelines de LLM.',
    ogLocale: 'es_CO',
    ogLocaleAlternate: 'en_US',
    twitterTitle: 'Kevin Gámez - Founding Engineer en Enttor',
    twitterDescription:
      'Founding engineer en enttor.ai. Outbound con IA, automatización de navegador, pipelines de LLM.',
    includeJsonLd: true,
    brandHref: '/es/',
    langSwitchHref: '/',
    langSwitchHreflang: 'en',
    langSwitchAriaLabel: 'Switch to English',
    langSwitchLabelHtml: 'EN · <b>ES</b>',
    skip: 'Saltar al contenido',
    hreflang: [
      { lang: 'en', href: 'https://kevingamez.co/' },
      { lang: 'es', href: 'https://kevingamez.co/es/' },
      { lang: 'x-default', href: 'https://kevingamez.co/' },
    ],
  },
  nav: {
    about: 'Sobre mí',
    stack: 'Stack',
    experience: 'Experiencia',
    work: 'Proyectos',
    github: 'GitHub',
    devMode: 'Modo dev',
    sayHi: 'Escríbeme ↗',
  },
  hero: {
    metaRole: 'Founding engineer @ Enttor',
    metaPlace: 'Bogotá',
    titleHtml: 'Hola',
    lede: 'Soy founding engineer en <b>Enttor</b>, donde construimos outbound con IA: automatización de navegador y\n            pipelines de OpenAI que encuentran y califican prospectos. Antes lancé un marketplace de e-commerce en\n            <b>Samsam</b>. Maestría en deep learning en la Universidad de los Andes.',
    stat1Num: '02',
    stat1Label: 'Startups como founding engineer',
    stat2Num: '07',
    stat2Label: 'Años en GitHub',
    portraitAlt: 'Kevin Gámez frente a Royce Hall, UCLA',
    scrollDown: 'Sigue bajando',
    btnGetInTouch: 'Hablemos',
    pauseTitle: 'pausar / reproducir',
    resetTitle: 're-sembrar aleatorio',
    stampGlider: 'planeador',
    stampLwss: 'nave',
    stampPulsar: 'púlsar',
    stampGun: 'cañón gosper',
    stampClear: 'limpiar',
    gen: 'gen',
    alive: 'vivas',
    fps: 'fps',
    golCaptionHtml:
      '<b>Juego de la vida de Conway</b> · un autómata celular de cero jugadores. Cada celda vive, muere o nace según el número de sus 8 vecinas (B3/S23). Click para sembrar un patrón. <a href="https://es.wikipedia.org/wiki/Juego_de_la_vida" target="_blank" rel="noopener">más info →</a>',
    golAriaLabel: 'Simulación del Juego de la vida de Conway',
  },
  about: {
    secNum: 'Sobre mí',
    titleHtml: 'Sobre mí.',
    blurb: 'Founding engineer, full-stack, egresado de deep learning.',
    p1Html:
      'Soy ingeniero de software, de Bogotá. En <b>Enttor</b> construí el motor de outbound con IA desde cero: la\n              automatización de navegador que encuentra prospectos en Instagram y LinkedIn, los pipelines de OpenAI que\n              los califican, los dashboards en Next.js donde todo vive, y las APIs en NestJS y colas de Inngest que lo\n              sostienen.',
    p2Html:
      'Antes de Enttor fui founding engineer en <b>Samsam</b>, un marketplace de e-commerce con una app de React\n              Native para compradores, un panel en Next.js para comerciantes, todo sobre Prisma y Postgres. Trabajos\n              anteriores cruzaron analítica (pipelines SQL y dashboards en Power BI para HR, riesgo y operaciones) y\n              deep learning sobre imágenes satelitales para detectar cultivos y riesgo ambiental.',
    p3Html:
      'B.Sc. en Ingeniería de Sistemas y Computación y M.Sc. en Ingeniería de Información, ambas en la\n              <b>Universidad de los Andes</b>, con especialización en deep learning y un minor en Management.',
    qfBased: 'Ubicación',
    qfBasedV: 'Bogotá, Colombia',
    qfRole: 'Rol',
    qfRoleV: 'Founding engineer @ enttor.ai',
    qfStack: 'Stack favorito',
    qfStackV: 'TypeScript · Next.js · Postgres',
    qfObsessed: 'Cacharreando con',
    qfObsessedV: 'Browser automation &amp; pipelines de LLM',
  },
  stack: {
    secNum: 'Stack',
    titleHtml: 'Las herramientas con las que construyo.',
    blurb: 'El stack detrás del motor de outbound de Enttor y de este sitio.',
    cols: [
      { name: 'Lenguajes', items: ['TypeScript', 'Python', 'SQL', 'Swift'] },
      { name: 'Frameworks', items: ['Next.js', 'React Native', 'NestJS', 'Astro'] },
      { name: 'Infraestructura', items: ['Postgres', 'Supabase', 'Vercel', 'Inngest'] },
      {
        name: 'IA & ML',
        items: [
          'Pipelines de OpenAI',
          'Automatización de navegador',
          'Deep learning',
          'Imágenes satelitales',
        ],
      },
    ],
  },
  experience: {
    secNum: 'Trayectoria',
    titleHtml: 'Dos startups y una maestría.',
    blurb:
      'Ingeniero fundador en Samsam y luego en Enttor. La maestría en deep learning fue en paralelo con el primer trabajo.',
    e1Year: 'Jun 2025 · hoy',
    e1Meta: 'New York · remoto · outbound con IA',
    e1Desc:
      'Construí el sistema que encuentra prospectos en Instagram y LinkedIn y los califica con IA. Full-stack:\n                dashboards en Next.js, APIs en NestJS, colas en Inngest, todo sobre Vercel y Supabase.',
    e2Year: 'Feb 2024 · Mar 2025',
    e2Meta: 'Bogotá · plataforma de e-commerce',
    e2Desc:
      'Lancé los dos lados del marketplace: una app en React Native para compradores y un panel en Next.js para\n                comerciantes, sobre Prisma y Postgres.',
    e3Year: 'Ene 2024 · May 2025',
    e3RoleHtml:
      'M.Sc. Ingeniería de Información <span class="at">@ Universidad de los Andes</span>',
    e3Meta: 'Especialización en deep learning · TA de posgrado',
    e3Desc:
      'Entrené modelos de deep learning sobre imágenes satelitales para detectar cultivos y riesgo ambiental. En\n                paralelo, teaching assistant de posgrado.',
    e4Year: 'Ene 2019 · Dic 2023',
    e4RoleHtml:
      'B.Sc. Ingeniería de Sistemas y Computación <span class="at">@ Universidad de los Andes</span>',
    e4Meta: 'Minor en Management',
    e4Desc:
      'Cinco años en los fundamentos: sistemas, algoritmos, ML aplicado y un minor en Management. Side projects\n                en Python, TypeScript, Java y Swift en el camino.',
    achievementsTitle: 'Honores y certificaciones',
    achievementsBlurb: 'Una distinción nacional y dos certificaciones de AWS.',
    achievements: [
      {
        year: '2018',
        titleHtml: 'Distinción <i>Andrés Bello</i>',
        meta: 'Ministerio de Educación · Colombia · categoría nacional',
        desc: 'Otorgada por estar entre los mejores puntajes del examen Saber 11 a nivel nacional. Uno de los reconocimientos estudiantiles más altos del país.',
      },
      {
        year: '2022',
        titleHtml: 'AWS Academy <i>Cloud Developing</i>',
        meta: 'Certificación · Amazon Web Services',
        desc: 'Construir, desplegar y escalar apps cloud-native en AWS: IAM, Lambda, DynamoDB, S3 y el resto del kit.',
      },
      {
        year: '2021',
        titleHtml: 'AWS Academy <i>Cloud Foundations</i>',
        meta: 'Certificación · Amazon Web Services',
        desc: 'Fundamentos de AWS: servicios, seguridad, arquitectura y facturación.',
      },
    ],
  },
  work: {
    secNum: 'Proyectos',
    titleHtml: 'Cosas que he construido.',
    blurb: 'Lo que he construido en el trabajo y por mi cuenta.',
    p1Featured: '01 / Destacado',
    p1NameHtml: 'enttor.ai · <i>outbound con IA.</i>',
    p1ImageAlt:
      'Estación de trabajo de Kevin Gámez con el sitio de Enttor abierto en un portátil y código en un monitor',
    p1Desc:
      'El sistema encuentra prospectos en Instagram y LinkedIn y los califica con pipelines de OpenAI. Construí la automatización de navegador, los dashboards y el backend.',
    p1Link: 'Ver Enttor →',
    p2Name: 'este sitio',
    p2Desc: 'La página en la que estás. Open-source, construida con Astro y TypeScript.',
    p3Name: 'modo dev',
    p3Desc: 'Un easter egg estilo VS Code escondido en /dev: explorador, pestañas, terminal.',
    p4Name: 'consola claude',
    p4Desc:
      'La shell al final de esta página. Transmite respuestas de Claude a través de una función de Vercel.',
    allRepos: 'Todos los repositorios',
  },
  deck: {
    secNum: 'Elige una carta',
    titleHtml: 'Lo que un CV no cuenta.',
    blurb: 'Cinco cartas. Todo lo que dicen es verdad.',
    hint: 'Elige una carta',
    items: [
      {
        label: 'Cómo trabajo',
        statement: 'Habla simple.',
        bodyHtml:
          'De un post que escribí en LinkedIn: puedes ser un gran ingeniero y aun así ser pobre. No porque no sepas programar. Porque no sabes hablar simple. El post completo está en <a href="#writing">Escritos</a>.',
      },
      {
        label: 'Ahora mismo',
        statement: 'Outbound con IA en Enttor.',
        bodyHtml:
          'Automatización de navegador que encuentra prospectos en Instagram y LinkedIn, y pipelines de OpenAI que los califican. Next.js, NestJS, Inngest, Supabase.',
      },
      {
        label: 'En paralelo',
        statement: 'Este sitio es uno.',
        bodyHtml:
          'Open source, construido con Astro y TypeScript. Esconde un <a href="/dev/">modo dev</a> estilo VS Code y corre una <a href="#console">consola de Claude</a> de verdad.',
      },
      {
        label: 'Pregúntame por',
        statement: 'Automatización, pipelines, satélites.',
        bodyHtml:
          'Automatización de navegador a escala, pipelines de calificación con LLM, o los modelos de deep learning que entrené sobre imágenes satelitales en la maestría.',
      },
      {
        label: 'Fuera del teclado',
        statement: 'Correr y montar bici por Bogotá.',
        bodyHtml:
          'La <a href="#strava">sección de Strava</a> más abajo es en vivo: distancia, horas y el esfuerzo más largo de cada tipo, directo de la API.',
      },
    ],
  },
  github: {
    secNum: 'GitHub',
    titleHtml: 'Repos públicos y commits.',
    blurb: 'Repos, lenguajes y los últimos 12 meses de commits, directo de GitHub.',
    snapshot: 'github.com/kevingamez · actualizado a diario',
    publicRepos: 'repos',
    publicReposSub: 'públicos, privados y de orgs en los que he aportado',
    languagesShipped: 'lenguajes',
    languagesShippedSub: 'lenguajes principales por bytes',
    langLeads: 'va primero',
    langSecond: 'va segundo',
    yearsOnGithub: 'años en github',
    yearsOnGithubSub: 'desde abril de 2019',
    languageMix: 'mezcla de lenguajes',
    acrossPublicRepos: 'todos los repos en los que trabajo',
    contributionsTitle: 'Contribuciones · @kevingamez',
    last12Months: 'últimos 12 meses',
    less: 'Menos',
    more: 'Más',
    months: ['May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic', 'Ene', 'Feb', 'Mar', 'Abr'],
    dows: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
    statCommits: 'Commits · 12m',
    statCurrent: 'Racha actual',
    statLongest: 'Racha más larga',
    repoSiteDesc: 'Esta página, con código fuente.',
    repoSpaceDesc: 'Detección aérea de eventos de deforestación en la Amazonía.',
    repoChatDesc: 'Experimento de chat en TypeScript.',
    repoBudgetDesc: 'App de finanzas personales en Swift.',
    repoCloudDesc: 'Despliegues de servicios containerizados en Cloud Run.',
    repoFallbackDesc: 'Repositorio público en GitHub.',
  },
  strava: {
    secNum: 'Strava',
    titleHtml: 'Correr y montar bici.',
    blurb: 'Datos de Strava: bici, carrera y trail, con el esfuerzo más largo de cada tipo.',
    statKm: 'kilómetros',
    statMi: 'millas',
    statHours: 'horas en movimiento',
    statElevation: 'metros escalados',
    statElevationFt: 'pies escalados',
    statActivities: 'actividades',
    weeklyTitle: 'Distancia semanal',
    weeklyPeakLabel: 'pico',
    featuredLabel: 'Más larga',
    featDist: 'distancia',
    featElev: 'elevación',
    featTime: 'en movimiento',
    featSpeed: 'vel. media',
    featPace: 'ritmo',
    insightClimbLabel: 'Mayor desnivel',
    insightFastLabel: 'Más rápida',
    insightBiggestLabel: 'Mejor semana',
    insightClimbedLabel: 'Escalado',
    weekOf: 'semana del',
    heatmapTitle: 'Calendario de entreno',
    heatLess: 'Descanso',
    heatMore: 'Fuerte',
    recentTitle: 'Actividad reciente',
    viewOnStrava: 'Ver en Strava →',
    profileUrl: 'https://www.strava.com/athletes/70612862',
    sports: {
      Run: 'Carrera',
      TrailRun: 'Trail',
      VirtualRun: 'Carrera virtual',
      Ride: 'Bici',
      VirtualRide: 'Bici virtual',
      GravelRide: 'Gravel',
      MountainBikeRide: 'MTB',
      Swim: 'Natación',
      Walk: 'Caminata',
      Hike: 'Senderismo',
      Workout: 'Entreno',
      WeightTraining: 'Pesas',
      Yoga: 'Yoga',
    },
  },
  writing: {
    secNum: 'Escritos',
    titleHtml: 'Posts de LinkedIn.',
    blurb: 'Mis posts de LinkedIn, reproducidos tal cual.',
    reactionsLabel: 'reacciones',
    commentsLabel: 'comentarios',
    repostsLabel: 'reposts',
    readOn: 'Leer en LinkedIn',
    seeMore: '…ver más',
    seeLess: 'ver menos',
    more: 'Ver todos en LinkedIn →',
  },
  wanderings: {
    secNum: 'Andanzas',
    titleHtml: 'Un pequeño mapa de <i>donde he estado.</i>',
    blurb: 'Mueve, haz zoom, pasa el cursor. Los puntos calientan más donde pasé más tiempo.',
    countries: 'países',
    cities: 'lugares',
    since: 'desde',
  },
  console: {
    secNum: 'Consola',
    titleHtml: 'Prueba la shell. Pregúntale a la IA.',
    blurb:
      'Escribe un comando: <span class="ac">help</span>, <span class="ac">whoami</span>, <span class="ac">experience</span>… ¿Quieres conversar? <span class="ac">kevin "tu pregunta"</span> abre la IA.',
    promptLabel: 'kevin@gamez · ~',
    streaming: 'listo',
    greeting:
      'bienvenido · una pequeña shell que indexa este sitio. escribe <span class="ac">help</span> para ver comandos, o pregúntale a la IA: <span class="ac">kevin "¿qué hace enttor?"</span>',
    placeholder: 'escribe un comando, enter para enviar…',
    suggest1: 'help',
    suggest2: 'whoami',
    suggest3: 'experience',
    suggest4: 'kevin ¿qué hace enttor?',
    rateLimitMsg: 'demasiadas peticiones · intenta en un minuto.',
    errorMsg: 'algo falló. intenta de nuevo o recarga.',
  },
  contact: {
    titleHtml: '¿Encajamos? <i>Averigüémoslo</i>.',
    body: 'Una llamada de 30 minutos, sin slides. Trae el problema en su versión desordenada. O solo saluda.',
    btnEmail: 'kevingamez.kg@gmail.com →',
    btnDev: 'Abrir modo dev',
  },
  footer: {
    pBlurb: 'Founding engineer y egresado de deep learning. Hecho en Bogotá.',
    h4Sections: 'Secciones',
    sectionsAbout: 'Sobre mí',
    sectionsExperience: 'Experiencia',
    sectionsWork: 'Proyectos',
    sectionsGithub: 'GitHub',
    h4Elsewhere: 'En otros lados',
    elsewhereDev: 'Modo dev →',
    fonts: 'Tipografías Archivo y JetBrains Mono',
    estab: 'Est. 2026 · Bogotá',
  },
}
