// English home-page strings for the github, strava, writing, wanderings, console, contact, and footer sections.
import type { HomeStrings } from './home'

export const enSections: Pick<
  HomeStrings,
  'yearRun' | 'github' | 'strava' | 'writing' | 'wanderings' | 'console' | 'contact' | 'footer'
> = {
  yearRun: {
    statContributions: 'Contributions',
    statStreak: 'Day streak',
    statProjects: 'Products shipped',
    chartAlt:
      'Weekly GitHub contributions across the last year, with the products that were in active development underneath.',
    tipContributions: 'contributions',
    tipWeekOf: 'week of',
    tipNothing: 'nothing running',
    noteStreak: 'days without a gap',
    noteWeek: 'in one week',
    noteAtOnce: 'products running at once',
    noteBegins: 'begins',
  },
  github: {
    secNum: 'GitHub',
    titleHtml: 'The year, and what was running.',
    blurb:
      'Founding engineer means several products at once. The line is what I pushed, week by week. The bars are what it went into.',
    publicRepos: 'Repos',
    languageMix: 'language mix',
  },
  strava: {
    secNum: 'Strava',
    titleHtml: 'Running and riding.',
    blurb: 'Ride, run, and trail data from Strava, plus my longest of each.',
    statKm: 'kilometers',
    statMi: 'miles',
    statHours: 'hours moving',
    statElevation: 'meters climbed',
    statElevationFt: 'feet climbed',
    statActivities: 'activities',
    weeklyTitle: 'Weekly distance',
    weeklyPeakLabel: 'peak',
    featuredLabel: 'Longest',
    featDist: 'distance',
    featElev: 'elevation',
    featTime: 'moving time',
    featSpeed: 'avg speed',
    featPace: 'pace',
    insightClimbLabel: 'Biggest climb',
    insightFastLabel: 'Fastest',
    insightBiggestLabel: 'Biggest week',
    insightClimbedLabel: 'Climbed',
    weekOf: 'week of',
    heatmapTitle: 'Training calendar',
    heatLess: 'Rest',
    heatMore: 'Big',
    recentTitle: 'Recent activity',
    viewOnStrava: 'View on Strava →',
    profileUrl: 'https://www.strava.com/athletes/70612862',
    sports: {
      Run: 'Run',
      TrailRun: 'Trail run',
      VirtualRun: 'Virtual run',
      Ride: 'Ride',
      VirtualRide: 'Virtual ride',
      GravelRide: 'Gravel ride',
      MountainBikeRide: 'MTB',
      Swim: 'Swim',
      Walk: 'Walk',
      Hike: 'Hike',
      Workout: 'Workout',
      WeightTraining: 'Lifting',
      Yoga: 'Yoga',
    },
  },
  writing: {
    secNum: 'Writing',
    titleHtml: 'Posts from LinkedIn.',
    blurb: 'My LinkedIn posts, reproduced verbatim.',
    reactionsLabel: 'reactions',
    commentsLabel: 'comments',
    repostsLabel: 'reposts',
    readOn: 'Read on LinkedIn',
    seeMore: '…see more',
    seeLess: 'see less',
    more: 'See all on LinkedIn →',
  },
  wanderings: {
    secNum: 'Wanderings',
    titleHtml: 'A small heatmap of <i>where I’ve been.</i>',
    blurb: 'Pan, zoom, hover. The longer I spent in a place, the hotter it looks.',
    countries: 'countries',
    cities: 'places',
    since: 'since',
  },
  console: {
    secNum: 'Console',
    titleHtml: 'Try the shell. Or ask the AI a question.',
    blurb:
      'Type a command: <span class="ac">help</span>, <span class="ac">whoami</span>, <span class="ac">experience</span>… Want to ask something else? <span class="ac">kevin "your question"</span> sends it to the AI.',
    promptLabel: 'kevin@gamez, ~',
    streaming: 'ready',
    greeting:
      'welcome, a small shell for this site. type <span class="ac">help</span> for commands, or ask the AI directly: <span class="ac">kevin "what does enttor do?"</span>',
    placeholder: 'type a command, press enter…',
    suggest1: 'help',
    suggest2: 'whoami',
    suggest3: 'experience',
    suggest4: 'kevin what does enttor do?',
    rateLimitMsg: 'rate limited, try again in a minute.',
    errorMsg: 'something broke. try again or refresh.',
  },
  contact: {
    titleHtml: "Let's find out if we <i>should work together</i>.",
    body: 'A 30-minute call, no deck. Bring the messy version of the problem. Or just say hi.',
    btnEmail: 'kevingamez.kg@gmail.com →',
    btnShare: 'Share this page',
    ctaLabel: 'Open to founding-engineer roles',
    ctaEmail: 'Email me',
    shareAria: 'Share this page',
    shareCopied: 'Link copied',
    shareFailed: 'Copy failed',
    shareText: 'Kevin Gámez, founding engineer in Bogotá.',
  },
  footer: {
    pBlurb: "Founding engineer with a master's in deep learning. Site built in Bogotá.",
    h4Sections: 'Sections',
    sectionsAbout: 'About',
    sectionsExperience: 'Experience',
    sectionsWork: 'Work',
    sectionsGithub: 'GitHub',
    h4Elsewhere: 'Elsewhere',
    elsewhereDev: 'Dev mode →',
    elsewherePrivacy: 'Privacy',
    estab: 'Est. 2026, Bogotá',
    credits: 'Credits and licenses',
  },
}
