import type { HomeStrings } from './home'

export const es: HomeStrings = {
  meta: {
    htmlLang: 'es',
    title: 'Kevin Gámez - Founding Engineer en Enttor',
    description:
      'Kevin Gámez es founding engineer en Enttor, basado en Bogotá. Outbound con IA, automatización de navegador, pipelines de OpenAI, Next.js / NestJS / Postgres.',
    canonical: 'https://kevingamez.co/es/',
    ogUrl: 'https://kevingamez.co/es/',
    ogTitle: 'Kevin Gámez - Founding Engineer en Enttor',
    ogDescription:
      'Founding engineer en enttor.ai. Outbound con IA, automatización de navegador, pipelines de LLM.',
    ogLocale: 'es_CO',
    ogLocaleAlternate: 'en_US',
    twitterTitle: 'Kevin Gámez - Founding Engineer en Enttor',
    twitterDescription:
      'Founding engineer en enttor.ai. Outbound con IA, automatización de navegador, pipelines de LLM.',
    includeJsonLd: true,
    brandHref: '/es/',
    langSwitchHref: '/',
    langSwitchHreflang: 'en',
    langSwitchAriaLabel: 'Switch to English',
    langSwitchLabelHtml: 'EN · <b>ES</b>',
    skip: 'Saltar al contenido',
    hreflang: [
      { lang: 'en', href: 'https://kevingamez.co/' },
      { lang: 'es', href: 'https://kevingamez.co/es/' },
      { lang: 'x-default', href: 'https://kevingamez.co/' },
    ],
  },
  nav: {
    about: 'Sobre mí',
    experience: 'Experiencia',
    work: 'Proyectos',
    github: 'GitHub',
    devMode: 'Modo dev',
    sayHi: 'Saludar →',
  },
  hero: {
    metaRole: 'Founding engineer @ Enttor',
    metaPlace: 'Bogotá',
    titleHtml: 'Construyo cosas,<br />casi siempre <i>software.</i>',
    lede: 'Soy founding engineer en <b>Enttor</b>, donde usamos IA y automatización de navegador para que el outbound\n            de marketing realmente funcione. Antes lancé una plataforma de e-commerce en <b>Samsam</b>. Maestría en\n            deep learning en la Universidad de los Andes.',
    btnSeeWork: 'Ver proyectos →',
    btnGetInTouch: 'Hablemos',
    pauseTitle: 'pausar / reproducir',
    resetTitle: 're-sembrar aleatorio',
    stampGlider: 'planeador',
    stampLwss: 'nave',
    stampPulsar: 'púlsar',
    stampGun: 'cañón gosper',
    stampClear: 'limpiar',
    gen: 'gen',
    alive: 'vivas',
    fps: 'fps',
    golCaptionHtml:
      '<b>Juego de la vida de Conway</b> · un autómata celular de cero jugadores. Cada celda vive, muere o nace según el número de sus 8 vecinas (B3/S23). Reglas simples, patrones sorprendentes. Click para sembrar un patrón. <a href="https://es.wikipedia.org/wiki/Juego_de_la_vida" target="_blank" rel="noopener">más info →</a>',
    golAriaLabel: 'Simulación del Juego de la vida de Conway',
  },
  about: {
    secNum: 'Sobre mí',
    titleHtml: 'Un estudio de una persona.',
    blurb:
      'Founding engineer, full-stack, recién egresado de deep learning. La corta abajo; la larga, con café.',
    portraitAlt: 'Kevin Gámez frente a Royce Hall, UCLA',
    p1Html:
      'Soy ingeniero de software, de Bogotá. En <b>Enttor</b> construí el motor de outbound con IA desde cero: la\n              automatización de navegador que encuentra prospectos en Instagram y LinkedIn, los pipelines de OpenAI que\n              los califican, los dashboards en Next.js donde todo vive, y las APIs en NestJS y colas de Inngest que lo\n              sostienen.',
    p2Html:
      'Antes de Enttor fui founding engineer en <b>Samsam</b>, un marketplace de e-commerce con una app de React\n              Native para compradores, un panel en Next.js para comerciantes, todo sobre Prisma y Postgres. Trabajos\n              anteriores cruzaron analítica (pipelines SQL y dashboards en Power BI para HR, riesgo y operaciones) y\n              deep learning sobre imágenes satelitales para detectar cultivos y riesgo ambiental.',
    p3Html:
      'B.Sc. en Ingeniería de Sistemas y Computación y M.Sc. en Ingeniería de Información, ambas en la\n              <b>Universidad de los Andes</b>, con especialización en deep learning y un minor en Management.',
    qfBased: 'Ubicación',
    qfBasedV: 'Bogotá, Colombia',
    qfRole: 'Rol',
    qfRoleV: 'Founding engineer @ enttor.ai',
    qfStack: 'Stack favorito',
    qfStackV: 'TypeScript · Next.js · Postgres',
    qfObsessed: 'Cacharreando con',
    qfObsessedV: 'Browser automation &amp; pipelines de LLM',
  },
  experience: {
    secNum: 'Trayectoria',
    titleHtml: 'Dos startups y una maestría.',
    blurb:
      'Dos turnos como founding engineer, una maestría en deep learning, y los años en Uniandes que me enseñaron a\n            hacer shipping.',
    e1Year: 'Jun 2025 · hoy',
    e1Meta: 'New York · remoto · outbound con IA',
    e1Desc:
      'Construí el sistema que encuentra los prospectos correctos en Instagram y LinkedIn, los califica con IA y\n                arranca conversaciones reales, a escala. Full-stack: dashboards en Next.js, APIs en NestJS, colas en\n                Inngest, todo sobre Vercel y Supabase.',
    e2Year: 'Feb 2024 · Mar 2025',
    e2Meta: 'Bogotá · plataforma de e-commerce',
    e2Desc:
      'Lancé los dos lados del marketplace: una app en React Native para compradores y un panel en Next.js para\n                comerciantes. Bajé los tiempos de respuesta del backend un 10% y construí un sistema de alertas que\n                hizo visibles los errores críticos un 70% más rápido.',
    e3Year: 'Ene 2024 · May 2025',
    e3RoleHtml:
      'M.Sc. Ingeniería de Información <span class="at">@ Universidad de los Andes</span>',
    e3Meta: 'Especialización en deep learning · TA de posgrado',
    e3Desc:
      'Entrené modelos de deep learning sobre imágenes satelitales para detectar cultivos y riesgo ambiental. En\n                paralelo trabajé como teaching assistant de posgrado; diseñé labs, abrí horarios de consulta y ayudé a\n                pregrados a sacar sus primeros modelos.',
    e4Year: 'Ene 2019 · Dic 2023',
    e4RoleHtml:
      'B.Sc. Ingeniería de Sistemas y Computación <span class="at">@ Universidad de los Andes</span>',
    e4Meta: 'Minor en Management',
    e4Desc:
      'Cinco años en los fundamentos: sistemas, algoritmos, ML aplicado y un minor en Management. Side projects\n                en Python, TypeScript, Java y Swift en el camino.',
    achievementsTitle: 'Honores y certificaciones',
    achievementsBlurb: 'Algunos sellos en el camino.',
    achievements: [
      {
        year: '2018',
        titleHtml: 'Distinción <i>Andrés Bello</i>',
        meta: 'Ministerio de Educación · Colombia · categoría nacional',
        desc: 'Otorgada por estar entre los mejores puntajes del examen Saber 11 a nivel nacional. Uno de los reconocimientos estudiantiles más altos del país.',
      },
      {
        year: '2022',
        titleHtml: 'AWS Academy <i>Cloud Developing</i>',
        meta: 'Certificación · Amazon Web Services',
        desc: 'Construir, desplegar y escalar apps cloud-native en AWS: IAM, Lambda, DynamoDB, S3 y el resto del kit.',
      },
      {
        year: '2021',
        titleHtml: 'AWS Academy <i>Cloud Foundations</i>',
        meta: 'Certificación · Amazon Web Services',
        desc: 'Fundamentos de AWS: servicios, seguridad, arquitectura y el modelo de billing que decide cuáles de esos terminas usando.',
      },
    ],
  },
  work: {
    secNum: 'Proyectos',
    titleHtml: 'Cosas que he construido y <i>aún defiendo.</i>',
    blurb:
      'Una edición más cuidada de los sistemas detrás del CV: superficies de producto, loops de automatización y experimentos que siguen vivos.',
    p1Featured: '01 / Destacado',
    p1NameHtml: 'enttor.ai · <i>outbound con IA que sí corre.</i>',
    p1ImageAlt:
      'Estación de trabajo de Kevin Gámez con el sitio de Enttor abierto en un portátil y código en un monitor',
    p1Desc:
      'El sistema encuentra prospectos en Instagram y LinkedIn, los califica con pipelines de OpenAI y mueve el trabajo por dashboards, APIs y colas. Construí la automatización de navegador, la superficie de producto y el backend que lo mantiene andando.',
    p1Link: 'Ver Enttor →',
    p2Name: 'Laboratorio de autómatas',
    p2Desc:
      "Un sandbox de autómatas celulares en WebAssembly: Conway, Wireworld, Brian's Brain, Lenia. En tiempo real\n              sobre un millón de celdas, todo en el navegador. El hero de esta página usa una implementación hermana.",
    p3Name: 'Atlas de fractales',
    p3Desc:
      'Un atlas interactivo de fractales de tiempo de escape · Mandelbrot, Burning Ship, Julia, Newton · con zoom\n              profundo, esquemas de color y URLs compartibles. Un proyecto de fin de semana que se comió tres fines de\n              semana.',
    p4Name: 'Cuadernos de números',
    p4Desc:
      'Recorridos de teoría de números como cuadernos Jupyter en vivo: espiral de Ulam, parejas de Goldbach, la\n              escalera de Riemann. Lo usan algunos profesores de matemáticas que admiro.',
    p5Name: 'este sitio',
    p5Desc:
      'La página en la que estás. Open-source, construida poco a poco, y un lugar para poner matemáticas que me\n              parecen bellas al lado de software del que estoy orgulloso.',
  },
  github: {
    secNum: 'GitHub',
    titleHtml: 'Código que dejo a la vista.',
    blurb: 'Los repos, los lenguajes y un año de commits reales, directo de GitHub.',
    snapshot: 'github.com/kevingamez · actualizado a diario',
    publicRepos: 'repos en los que ship',
    publicReposSub: 'públicos, privados y de orgs en los que he aportado',
    languagesShipped: 'lenguajes embarcados',
    languagesShippedSub: 'lenguajes principales por bytes',
    langLeads: 'va primero',
    langSecond: 'va segundo',
    yearsOnGithub: 'años en github',
    yearsOnGithubSub: 'desde abril de 2019',
    languageMix: 'mezcla de lenguajes',
    acrossPublicRepos: 'todos los repos en los que trabajo',
    contributionsTitle: 'Contribuciones · @kevingamez',
    last12Months: 'últimos 12 meses',
    less: 'Menos',
    more: 'Más',
    months: ['May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic', 'Ene', 'Feb', 'Mar', 'Abr'],
    dows: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
    statCommits: 'Commits · 12m',
    statCurrent: 'Racha actual',
    statLongest: 'Racha más larga',
    repoSiteDesc: 'Esta página, con código fuente.',
    repoSpaceDesc: 'Detección aérea de eventos de deforestación en la Amazonía.',
    repoChatDesc: 'Experimento de chat en TypeScript.',
    repoBudgetDesc: 'App de finanzas personales en Swift.',
    repoCloudDesc: 'Despliegues de servicios containerizados en Cloud Run.',
    repoFallbackDesc: 'Repositorio público en GitHub.',
  },
  strava: {
    secNum: 'Strava',
    titleHtml: 'Desconectado, pero en movimiento.',
    blurb:
      'Una mirada en vivo a cada salida en bici, carrera y trail - el esfuerzo más largo de cada uno, directo de Strava.',
    statKm: 'kilómetros',
    statMi: 'millas',
    statHours: 'horas en movimiento',
    statElevation: 'metros escalados',
    statElevationFt: 'pies escalados',
    statActivities: 'actividades',
    weeklyTitle: 'Distancia semanal',
    weeklyPeakLabel: 'pico',
    featuredLabel: 'Más larga',
    featDist: 'distancia',
    featElev: 'elevación',
    featTime: 'en movimiento',
    featSpeed: 'vel. media',
    featPace: 'ritmo',
    insightClimbLabel: 'Mayor desnivel',
    insightFastLabel: 'Más rápida',
    insightBiggestLabel: 'Mejor semana',
    insightClimbedLabel: 'Escalado',
    climbedCompare: '× la Torre Eiffel',
    weekOf: 'semana del',
    heatmapTitle: 'Calendario de entreno',
    heatLess: 'Descanso',
    heatMore: 'Fuerte',
    recentTitle: 'Actividad reciente',
    viewOnStrava: 'Ver en Strava →',
    profileUrl: 'https://www.strava.com/athletes/70612862',
    sports: {
      Run: 'Carrera',
      TrailRun: 'Trail',
      VirtualRun: 'Carrera virtual',
      Ride: 'Bici',
      VirtualRide: 'Bici virtual',
      GravelRide: 'Gravel',
      MountainBikeRide: 'MTB',
      Swim: 'Natación',
      Walk: 'Caminata',
      Hike: 'Senderismo',
      Workout: 'Entreno',
      WeightTraining: 'Pesas',
      Yoga: 'Yoga',
    },
  },
  writing: {
    secNum: 'Escritos',
    titleHtml: 'Notas desde la trinchera.',
    blurb: 'Ensayos cortos sobre ingeniería, startups y cómo se siente realmente sacar producto.',
    reactionsLabel: 'reacciones',
    commentsLabel: 'comentarios',
    repostsLabel: 'reposts',
    readOn: 'Leer en LinkedIn',
    seeMore: '…ver más',
    seeLess: 'ver menos',
    more: 'Ver todos en LinkedIn →',
  },
  wanderings: {
    secNum: 'Andanzas',
    titleHtml: 'Un pequeño mapa de <i>donde he estado.</i>',
    blurb:
      'Mueve, haz zoom, pasa el cursor. Los puntos calientan más donde pasé más tiempo; Bogotá brilla por algo.',
    countries: 'países',
    cities: 'lugares',
    since: 'desde',
  },
  console: {
    secNum: 'Consola',
    titleHtml: 'Prueba la shell. Pregúntale a la IA.',
    blurb:
      'Escribe un comando: <span class="ac">help</span>, <span class="ac">whoami</span>, <span class="ac">experience</span>… ¿Quieres conversar? <span class="ac">kevin "tu pregunta"</span> abre la IA.',
    promptLabel: 'kevin@gamez · ~',
    streaming: 'listo',
    greeting:
      'bienvenido · una pequeña shell que indexa este sitio. escribe <span class="ac">help</span> para ver comandos, o pregúntale a la IA: <span class="ac">kevin "¿qué hace enttor?"</span>',
    placeholder: 'escribe un comando, enter para enviar…',
    suggest1: 'help',
    suggest2: 'whoami',
    suggest3: 'experience',
    suggest4: 'kevin ¿qué hace enttor?',
    rateLimitMsg: 'demasiadas peticiones · intenta en un minuto.',
    errorMsg: 'algo falló. intenta de nuevo o recarga.',
  },
  contact: {
    titleHtml: 'Un gusto <i>conocerte</i>.',
    body: 'Este es solo un rincón de internet para que me conozcas un poco. Si algo de aquí te resonó y quieres\n          saludar, el inbox está abierto.',
    btnEmail: 'kevingamez.kg@gmail.com →',
    btnDev: 'Abrir modo dev',
  },
  footer: {
    h4Page: 'La página',
    pBlurb:
      'Founding engineer, recién graduado de deep learning y estudiante entusiasta · aunque mediocre · de\n              matemáticas. Hecho a mano en Bogotá.',
    h4Sections: 'Secciones',
    sectionsAbout: 'Sobre mí',
    sectionsExperience: 'Experiencia',
    sectionsWork: 'Proyectos',
    sectionsGithub: 'GitHub',
    h4Elsewhere: 'En otros lados',
    elsewhereDev: 'Modo dev →',
    fonts: 'Tipografías Fraunces e Hanken Grotesk',
    estab: 'Est. 2026 · Bogotá',
  },
}
