// Spanish home-page strings for the github, strava, writing, wanderings, console, contact, and footer sections.
import type { HomeStrings } from './home'

export const esSections: Pick<
  HomeStrings,
  'yearRun' | 'github' | 'strava' | 'writing' | 'wanderings' | 'console' | 'contact' | 'footer'
> = {
  yearRun: {
    secNum: 'GitHub',
    titleHtml: 'El año, y qué estaba corriendo.',
    blurb:
      'La línea es lo que empujé, semana a semana. Las barras de abajo son los productos que estaban vivos entonces, así que los picos tienen causa.',
    statContributions: 'Contribuciones',
    statStreak: 'Días seguidos',
    statProjects: 'Productos',
    chartAlt:
      'Contribuciones semanales en GitHub del último año, con los productos que estaban en desarrollo debajo.',
    tipContributions: 'contribuciones',
    tipWeekOf: 'semana del',
    tipNothing: 'nada en curso',
    noteStreak: 'días sin fallar uno',
    noteWeek: 'en una semana',
    noteAtOnce: 'productos a la vez',
    noteBegins: 'arranca',
  },
  github: {
    secNum: 'GitHub',
    titleHtml: 'Repos públicos y commits.',
    blurb: 'Repos, lenguajes y los últimos 12 meses de commits, directo de GitHub.',
    snapshot: 'github.com/kevingamez',
    publicRepos: 'repos',
    publicReposSub: 'públicos y privados, más los de organizaciones donde he aportado',
    languagesShipped: 'lenguajes',
    languagesShippedSub: 'mis lenguajes principales, medidos por bytes de código',
    langLeads: 'va primero',
    langSecond: 'va segundo',
    yearsOnGithub: 'años en github',
    yearsOnGithubSub: 'desde abril de 2019',
    languageMix: 'mezcla de lenguajes',
    acrossPublicRepos: 'todos los repos en los que trabajo',
    contributionsTitle: 'Contribuciones, @kevingamez',
    last12Months: 'últimos 12 meses',
    less: 'Menos',
    more: 'Más',
    months: ['May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic', 'Ene', 'Feb', 'Mar', 'Abr'],
    dows: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
    statCommits: 'Commits, 12m',
    statCurrent: 'Racha actual',
    statLongest: 'Racha más larga',
    repoSiteDesc: 'Esta página, con código fuente.',
    repoSpaceDesc: 'Detección aérea de deforestación en la Amazonía.',
    repoChatDesc: 'Experimento de chat en TypeScript.',
    repoBudgetDesc: 'App de finanzas personales en Swift.',
    repoCloudDesc: 'Servicios en contenedores desplegados en Cloud Run.',
    repoFallbackDesc: 'Repositorio público en GitHub.',
  },
  strava: {
    secNum: 'Strava',
    titleHtml: 'Correr y montar bici.',
    blurb: 'Datos de Strava: bici, carrera y trail, con mi salida más larga de cada tipo.',
    statKm: 'kilómetros',
    statMi: 'millas',
    statHours: 'horas en movimiento',
    statElevation: 'metros de desnivel',
    statElevationFt: 'pies de desnivel',
    statActivities: 'actividades',
    weeklyTitle: 'Distancia semanal',
    weeklyPeakLabel: 'pico',
    featuredLabel: 'Más larga',
    featDist: 'distancia',
    featElev: 'elevación',
    featTime: 'en movimiento',
    featSpeed: 'vel. media',
    featPace: 'ritmo',
    insightClimbLabel: 'Mayor desnivel',
    insightFastLabel: 'Más rápida',
    insightBiggestLabel: 'Mejor semana',
    insightClimbedLabel: 'Escalado',
    weekOf: 'semana del',
    heatmapTitle: 'Calendario de entreno',
    heatLess: 'Descanso',
    heatMore: 'Fuerte',
    recentTitle: 'Actividad reciente',
    viewOnStrava: 'Ver en Strava →',
    profileUrl: 'https://www.strava.com/athletes/70612862',
    sports: {
      Run: 'Carrera',
      TrailRun: 'Trail',
      VirtualRun: 'Carrera virtual',
      Ride: 'Bici',
      VirtualRide: 'Bici virtual',
      GravelRide: 'Gravel',
      MountainBikeRide: 'MTB',
      Swim: 'Natación',
      Walk: 'Caminata',
      Hike: 'Senderismo',
      Workout: 'Entreno',
      WeightTraining: 'Pesas',
      Yoga: 'Yoga',
    },
  },
  writing: {
    secNum: 'Escritos',
    titleHtml: 'Posts de LinkedIn.',
    blurb: 'Mis posts de LinkedIn, reproducidos tal cual.',
    reactionsLabel: 'reacciones',
    commentsLabel: 'comentarios',
    repostsLabel: 'reposts',
    readOn: 'Leer en LinkedIn',
    seeMore: '…ver más',
    seeLess: 'ver menos',
    more: 'Ver todos en LinkedIn →',
  },
  wanderings: {
    secNum: 'Andanzas',
    titleHtml: 'Un pequeño mapa de <i>donde he estado.</i>',
    blurb: 'Mueve, haz zoom, pasa el cursor. Los puntos son más intensos donde pasé más tiempo.',
    countries: 'países',
    cities: 'lugares',
    since: 'desde',
  },
  console: {
    secNum: 'Consola',
    titleHtml: 'Prueba la shell. Pregúntale a la IA.',
    blurb:
      'Escribe un comando: <span class="ac">help</span>, <span class="ac">whoami</span>, <span class="ac">experience</span>… ¿Quieres preguntar otra cosa? <span class="ac">kevin "tu pregunta"</span> se la manda a la IA.',
    promptLabel: 'kevin@gamez, ~',
    streaming: 'listo',
    greeting:
      'bienvenido, una pequeña shell que busca dentro de este sitio. escribe <span class="ac">help</span> para ver comandos, o pregúntale a la IA: <span class="ac">kevin "¿qué hace enttor?"</span>',
    placeholder: 'escribe un comando…',
    suggest1: 'help',
    suggest2: 'whoami',
    suggest3: 'experience',
    suggest4: 'kevin ¿qué hace enttor?',
    rateLimitMsg: 'demasiadas peticiones, intenta en un minuto.',
    errorMsg: 'algo falló. intenta de nuevo o recarga.',
  },
  contact: {
    titleHtml: '¿Trabajamos juntos? <i>Hablemos</i>.',
    body: 'Una llamada de 30 minutos, sin slides. Tráelo como esté, aunque esté desordenado. O solo saluda.',
    btnEmail: 'kevingamez.kg@gmail.com →',
    btnDev: 'Abrir modo dev',
  },
  footer: {
    pBlurb: 'Founding engineer con maestría en deep learning. Sitio hecho en Bogotá.',
    h4Sections: 'Secciones',
    sectionsAbout: 'Sobre mí',
    sectionsExperience: 'Experiencia',
    sectionsWork: 'Proyectos',
    sectionsGithub: 'GitHub',
    h4Elsewhere: 'En otros lados',
    elsewhereDev: 'Modo dev →',
    elsewherePrivacy: 'Privacidad',
    fonts: 'Tipografías Inter y JetBrains Mono',
    estab: 'Est. 2026, Bogotá',
  },
}
