import type { HomeStrings } from './home'
import { enSections } from './home-en-sections'

export const en: HomeStrings = {
  meta: {
    htmlLang: 'en',
    title: "Kevin Gámez - Founding Engineer, open to what's next",
    description:
      "Kevin Gámez is a founding engineer in Bogotá, Colombia, open to what's next. Browser automation, LLM pipelines, TypeScript, Next.js, NestJS, Postgres.",
    canonical: 'https://kevingamez.co/',
    ogUrl: 'https://kevingamez.co/',
    ogTitle: "Kevin Gámez - Founding Engineer, open to what's next",
    ogDescription:
      "Founding engineer in Bogotá, open to what's next. Browser automation, LLM pipelines, full-stack TypeScript.",
    ogLocale: 'en_US',
    ogLocaleAlternate: 'es_CO',
    twitterTitle: "Kevin Gámez - Founding Engineer, open to what's next",
    twitterDescription:
      "Founding engineer in Bogotá, open to what's next. Browser automation, LLM pipelines, full-stack TypeScript.",
    includeJsonLd: true,
    brandHref: '/',
    skip: 'Skip to content',
    hreflang: [
      { lang: 'en', href: 'https://kevingamez.co/' },
      { lang: 'es', href: 'https://kevingamez.co/es/' },
      { lang: 'x-default', href: 'https://kevingamez.co/' },
    ],
  },
  nav: {
    about: 'About',
    experience: 'Experience',
    work: 'Work',
    github: 'GitHub',
    resume: 'Résumé',
    sayHi: 'Email me ↗',
  },
  hero: {
    metaRole: "Founding engineer, open to what's next",
    metaPlace: 'Bogotá, Colombia',
    weatherLabels:
      '{"clear": "clear", "partly cloudy": "partly cloudy", "cloudy": "cloudy", "fog": "fog", "drizzle": "drizzle", "rain": "rain", "showers": "showers", "snow": "snow", "storm": "storm"}',
    titleHtml: 'Hello',
    lede: "I'm a founding engineer in Bogotá, open to what's next. Most recently at <b>Enttor</b>, where I built\n            the AI ad-creation platform and the browser agents behind its outbound. Before that, an e-commerce\n            marketplace at <b>Samsam</b>. M.Sc. in deep learning from Universidad de los Andes.",
    stat1Num: '02',
    stat1Label: 'Startups as founding engineer',
    stat2Num: '07',
    stat2Label: 'Years on GitHub',
    scrollDown: 'Scroll down',
    btnGetInTouch: 'Get in touch',
    pauseTitle: 'pause/play',
    resetTitle: 'random reseed',
    stampGlider: 'glider',
    stampLwss: 'spaceship',
    stampPulsar: 'pulsar',
    stampGun: 'gosper gun',
    stampClear: 'clear',
    gen: 'gen',
    alive: 'alive',
    fps: 'fps',
    golCaptionHtml:
      '<b>Conway\'s Game of Life</b>, a zero-player cellular automaton. Each cell lives, dies, or is born from the count of its 8 neighbors (B3/S23). Click to seed a stamp. <a href="https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life" target="_blank" rel="noopener">read more →</a>',
    golAriaLabel: "Conway's Game of Life simulation",
  },
  about: {
    secNum: 'About',
    titleHtml: 'About me.',
    blurb: "Full-stack founding engineer with a master's in deep learning.",
    p1Html:
      "I'm a software engineer from Bogotá. At <b>Enttor</b> I built the AI outbound system: the browser\n              automation that found prospects on Instagram and LinkedIn, the OpenAI pipelines that qualified them, the\n              Next.js dashboards, and the NestJS APIs and Inngest queues behind them.",
    p2Html:
      'Before Enttor I was founding engineer at <b>Samsam</b>, an e-commerce marketplace with a React Native app for\n              shoppers, a Next.js dashboard for merchants, all on Prisma and Postgres. Earlier work spanned analytics\n              (SQL pipelines and Power BI dashboards for HR, risk, and operations) and deep learning on satellite\n              imagery to spot croplands and flag environmental risk.',
    p3Html:
      'B.Sc. in Systems and Computing and M.Sc. in Information Engineering, both from <b>Universidad de los Andes</b\n              >, with a deep-learning specialization and a minor in management.',
    qfBased: 'Based',
    qfBasedV: 'Bogotá, Colombia',
    qfRole: 'Role',
    qfRoleV: "Founding engineer, open to what's next",
    qfStack: 'Stack of choice',
    qfStackV: 'TypeScript, Next.js, Postgres',
    qfObsessed: 'Tinkering with',
    qfObsessedV: 'Browser automation and LLM pipelines',
  },
  experience: {
    secNum: 'Experience',
    titleHtml: "Two startups and a master's.",
    blurb:
      "Founding engineer at Samsam, then at Enttor. I did the master's in deep learning while working the first job.",
    openHint: 'Click a row to open it',
    roles: [
      {
        dates: 'Jun 2025, Jul 2026',
        place: 'New York, remote',
        roleHtml: 'Founding engineer <span class="at">@ Enttor</span>',
        logo: '/logos/enttor.png',
        summary: 'Built the AI outbound engine end to end: automation, pipelines, dashboards.',
        desc: 'Browser automation sourced prospects on Instagram and LinkedIn, OpenAI pipelines filtered them and drafted the messages, and the campaigns sent them at scale. Next.js dashboards, NestJS APIs and Inngest queues on Vercel and Supabase, from scratch.',
        ledger: [
          { label: 'API routes', value: '132' },
          { label: 'Postgres schemas', value: '4' },
          { label: 'Agent tools, Meta and TikTok', value: '165' },
          { label: 'Platforms automated', value: '4' },
        ],
        stackLabel: 'Built with',
        stack: ['TypeScript', 'Next.js', 'NestJS', 'Inngest', 'Supabase', 'Playwright'],
      },
      {
        dates: 'Feb 2024, Mar 2025',
        place: 'Bogotá',
        roleHtml: 'Founding engineer <span class="at">@ Samsam</span>',
        logo: '/logos/samsam.png',
        summary:
          'Shipped both sides of an e-commerce marketplace: shopper app and merchant dashboard.',
        desc: 'A React Native app for shoppers and a Next.js dashboard for merchants, on Prisma and Postgres. I shipped both sides.',
        ledger: [
          { label: 'Marketplace sides shipped', value: '2' },
          { label: 'Zero to launch', value: '14 mo' },
          { label: 'Apps', value: 'iOS, Android, web' },
          { label: 'Data layer', value: 'Prisma, Postgres' },
        ],
        stackLabel: 'Built with',
        stack: ['React Native', 'Next.js', 'Prisma', 'Postgres'],
      },
      {
        dates: 'Jan 2024, May 2025',
        place: 'Bogotá',
        roleHtml:
          'M.Sc. Information Engineering <span class="at">@ Universidad de los Andes</span>',
        logo: '/logos/uniandes.svg',
        summary: 'Deep-learning specialization, taken while working the first job. Graduate TA.',
        desc: 'Trained deep-learning models on satellite imagery to spot croplands and flag environmental risk. Graduate TA at the same time.',
        ledger: [
          { label: 'Focus', value: 'Satellite imagery' },
          { label: 'Role', value: 'Graduate TA' },
          { label: 'Specialization', value: 'Deep learning' },
          { label: 'Overlap with work', value: 'Full-time' },
        ],
        stackLabel: 'Worked in',
        stack: ['Python', 'SQL', 'Deep learning'],
      },
      {
        dates: 'Jan 2019, Dec 2023',
        place: 'Bogotá',
        roleHtml: 'B.Sc. Systems and Computing <span class="at">@ Universidad de los Andes</span>',
        logo: '/logos/uniandes.svg',
        summary: 'Five years on the foundations, plus a minor in management.',
        desc: 'Systems, algorithms and applied ML, plus a minor in management. Side projects in Python, TypeScript, Java and Swift along the way.',
        ledger: [
          { label: 'Minor', value: 'Management' },
          { label: 'Foundations', value: '5 yrs' },
          { label: 'Emphasis', value: 'Systems, algorithms' },
          { label: 'Side projects', value: '4 languages' },
        ],
        stackLabel: 'Worked in',
        stack: ['Python', 'TypeScript', 'Java', 'Swift'],
      },
    ],
    achievementsTitle: 'Honors &amp; certifications',
    achievementsBlurb: 'A national distinction and two AWS certifications.',
    achievements: [
      {
        year: '2018',
        logo: '/logos/mineducacion.svg',
        titleHtml: 'Andrés Bello <i>National Distinction</i>',
        meta: 'Ministry of Education, Colombia',
        desc: 'Awarded by the Ministry of Education for a top-ranked score on Colombia’s national high-school exit exam (Saber 11).',
      },
      {
        year: '2022',
        logo: '/logos/aws.svg',
        titleHtml: 'AWS Academy <i>Cloud Developing</i>',
        meta: 'Certification, Amazon Web Services',
        desc: 'Building, deploying, and scaling apps on AWS: IAM, Lambda, DynamoDB, S3.',
      },
      {
        year: '2021',
        logo: '/logos/aws.svg',
        titleHtml: 'AWS Academy <i>Cloud Foundations</i>',
        meta: 'Certification, Amazon Web Services',
        desc: 'AWS fundamentals: core services, security, architecture, and pricing.',
      },
    ],
  },
  work: {
    secNum: 'Selected work',
    titleHtml: "Things I've built.",
    blurb: 'Product, infrastructure, and a few things on the side.',
    p1NameHtml: 'AI Ad Studio, <i>ads that build themselves.</i>',
    p1ImageAlt:
      'Kevin Gámez workstation with the Enttor site open on a laptop and code on a monitor',
    p1Desc:
      "Enttor's last product. Give it a brand's website and it scrapes the logos, colors and fonts, writes ad concepts with Claude, renders finished images, then checks its own work with a vision pass. It also takes an existing ad apart into editable layers: OCR and instance segmentation recover the real text, fonts and boxes, so a media buyer edits on a canvas instead of rebuilding from scratch. The CV pipeline runs on GPUs.",
    p1Meta: 'Next.js, NestJS, OpenAI, Inngest, Supabase',
    projects: [
      {
        name: 'Slack Agent',
        desc: 'The same product with a second front door: a Slack bot media buyers talk to like a coworker. 165 tools across the Meta and TikTok ad APIs, so it launches campaigns, diagnoses creative fatigue and moves budget instead of just answering questions. Launching an ad takes three steps instead of the thirty clicks Ads Manager asks for, and creatives import in bulk straight from a Drive folder.',
        meta: 'Claude tool use, Meta and TikTok APIs, Postgres',
      },
      {
        name: 'Enttor Platform',
        desc: 'Two years of the GTM product: it sourced prospects from Instagram and LinkedIn engagement, wrote personalized DMs with AI, auto-replied through Meta webhooks and tracked it all in one inbox. 132 API routes over four Postgres schemas.',
        meta: 'Next.js, Supabase, Inngest',
      },
      {
        name: 'MakeMotionGraphics',
        desc: 'Text to looping motion graphics. Claude writes a self-contained HTML scene, screenshots it in headless Chrome to see its own output, patches it, and only then finalizes. A parallel frame pipeline records the result to MP4.',
        meta: 'Agentic loop, Puppeteer, ffmpeg',
      },
      {
        name: 'LinkedIn Editor',
        desc: 'A chat-first editor for LinkedIn posts. You paste a draft and argue with Claude about the hook until it lands, grounded by retrieval over a corpus of posts that actually performed.',
        meta: 'pgvector RAG, Next.js',
      },
      {
        name: 'Browser Automation Infrastructure',
        desc: 'The self-hosted backend behind the outreach: Node services on a Mac Mini in Bogotá that hold real logged-in sessions on four platforms, scrape engagement and send messages at human rates. I contributed; two teammates led it.',
        meta: 'Playwright, BullMQ, Redis',
      },
      {
        name: 'Samsam',
        desc: 'Before Enttor. A shopping marketplace: a React Native app for shoppers and a Next.js dashboard for merchants, on Prisma and Postgres. I shipped both sides.',
        meta: 'React Native, Prisma',
      },
    ],
    allRepos: 'All repositories',
  },
  deck: {
    momentsLabel: 'Moments',
    momentsFull: 'Fullscreen',
    momentsClose: 'Click or Esc to let it go',
    secNum: 'The deck',
    titleHtml: 'The parts a CV leaves out.',
    blurb: 'Nine photographs. Everything on them is true.',
    hint: 'Pick a card',
  },
  ...enSections,
}
